
spring:
  datasource:
    url: 'jdbc:h2:mem:cysec-modeller'
    username: cysec
    password: cysec
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    open-in-view: true
