name: Build and push Docker image

on:
  workflow_dispatch:

jobs:
  docker-build:
    name: Build image and push to CR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Get version
        id: get-version
        run: |
          echo ::set-output name=project-version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo Version is "${{ steps.get-version.outputs.project-version }}"

      - name: Build with Maven
        run: mvn -B clean package verify

      - name: Docker build
        run: |
          docker build ./cysec-modeller-app -t ghcr.io/cysec-platform/cysec-modeller:latest -t ghcr.io/cysec-platform/cysec-modeller:${{ steps.get-version.outputs.project-version }}

      - name: Login to CR
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to CR
        run: |
          docker push ghcr.io/cysec-platform/cysec-modeller:${{ steps.get-version.outputs.project-version }}
          docker push ghcr.io/cysec-platform/cysec-modeller:latest
